name: Lighthouse CI

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'

jobs:
  lhci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Lighthouse CI on production
        uses: treosh/lighthouse-ci-action@v12
        with:
          urls: |
            https://pitchperfectai.ai/
            https://pitchperfectai.ai/demo
            https://pitchperfectai.ai/signup
          runs: 3
          uploadArtifacts: true
          temporaryPublicStorage: true
