
import React from 'react';
import { Bot } from 'lucide-react';
import { Tooltip, TooltipContent, TooltipTrigger } from '@/components/ui/tooltip';
import { cn } from '@/lib/utils';

export interface AIContentBadgeProps {
  type?: 'badge' | 'icon' | 'label';
  className?: string;
  tooltipContent?: string;
  position?: 'top-right' | 'inline';
  size?: 'sm' | 'md' | 'lg';
}

/**
 * A component to indicate AI-generated content throughout the app
 * Used to comply with Google Play guidelines for AI transparency
 */
const AIContentBadge = ({
  type = 'badge',
  className,
  tooltipContent = 'This content was generated by AI',
  position = 'top-right',
  size = 'md',
}: AIContentBadgeProps) => {
  const sizeClasses = {
    sm: 'text-xs',
    md: 'text-sm',
    lg: 'text-base',
  };

  const iconSizes = {
    sm: 12,
    md: 14,
    lg: 16,
  };

  const positionClasses = {
    'top-right': 'absolute top-2 right-2',
    'inline': 'inline-flex ml-1',
  };

  if (type === 'badge') {
    return (
      <Tooltip>
        <TooltipTrigger asChild>
          <div 
            className={cn(
              'bg-purple-100 text-purple-800 rounded-full px-2 py-0.5 flex items-center gap-1 w-fit',
              sizeClasses[size],
              position && positionClasses[position],
              className
            )}
          >
            <Bot size={iconSizes[size]} />
            <span>AI Generated</span>
          </div>
        </TooltipTrigger>
        <TooltipContent side="top">
          <p className="max-w-xs text-sm">{tooltipContent}</p>
        </TooltipContent>
      </Tooltip>
    );
  }

  if (type === 'icon') {
    return (
      <Tooltip>
        <TooltipTrigger asChild>
          <div 
            className={cn(
              'bg-purple-100 text-purple-800 rounded-full p-1',
              position && positionClasses[position],
              className
            )}
          >
            <Bot size={iconSizes[size]} />
          </div>
        </TooltipTrigger>
        <TooltipContent side="top">
          <p className="max-w-xs text-sm">{tooltipContent}</p>
        </TooltipContent>
      </Tooltip>
    );
  }

  // Label type (simple text with icon)
  return (
    <Tooltip>
      <TooltipTrigger asChild>
        <span 
          className={cn(
            'inline-flex items-center gap-1 text-purple-800',
            sizeClasses[size],
            className
          )}
        >
          <Bot size={iconSizes[size]} />
          <span>AI</span>
        </span>
      </TooltipTrigger>
      <TooltipContent side="top">
        <p className="max-w-xs text-sm">{tooltipContent}</p>
      </TooltipContent>
    </Tooltip>
  );
};

export default AIContentBadge;
