
import React from 'react';
import { Card, CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { useToast } from '@/components/ui/use-toast';
import AIContentBadge from './AIContentBadge';

interface AISuggestionCardProps {
  title: string;
  description: string;
  type: 'tip' | 'script';
  onApply?: (title: string, description: string, type: 'tip' | 'script') => void;
}

const AISuggestionCard = ({ title, description, type, onApply }: AISuggestionCardProps) => {
  const { toast } = useToast();
  const isScript = type === 'script';
  
  const handleApply = () => {
    if (onApply) {
      onApply(title, description, type);
    } else {
      // Fallback toast notification if no handler provided
      toast({
        title: isScript ? "Script Applied" : "Tip Applied",
        description: isScript 
          ? "Script has been copied to your clipboard" 
          : "This tip has been noted for your practice sessions",
      });

      // Copy to clipboard as fallback behavior
      navigator.clipboard.writeText(description)
        .then(() => {
          toast({
            title: "Copied to clipboard",
            description: `${isScript ? "Script" : "Tip"} has been copied to your clipboard`,
          });
        })
        .catch(err => {
          console.error("Failed to copy text: ", err);
          toast({
            title: "Copy failed",
            description: "Please try selecting and copying the text manually",
            variant: "destructive",
          });
        });
    }
  };
  
  return (
    <Card className={`overflow-hidden ${isScript ? 'border-purple-300' : 'border-brand-blue'} relative`}>
      <div className={`h-2 ${isScript ? 'bg-purple-500' : 'bg-brand-blue'}`}></div>
      <AIContentBadge 
        type="icon" 
        position="top-right"
        tooltipContent={isScript ? "This sales script was generated by AI" : "This sales tip was generated by AI"}
      />
      <CardContent className="p-6">
        <div className="flex justify-between items-start mb-4">
          <h3 className="font-medium text-lg text-brand-dark">{title}</h3>
          <span className={`text-xs px-2 py-1 rounded-full ${
            isScript ? 'bg-purple-100 text-purple-700' : 'bg-brand-blue/30 text-blue-700'
          }`}>
            {isScript ? 'Script' : 'Tip'}
          </span>
        </div>
        <p className="text-brand-dark/70 mb-4 text-sm">
          {description}
        </p>
        <div className="flex justify-end">
          <Button 
            variant="ghost" 
            size="sm" 
            className={`text-xs ${
              isScript ? 'text-purple-700 hover:bg-purple-100' : 'text-blue-700 hover:bg-brand-blue/20'
            }`}
            onClick={handleApply}
          >
            {isScript ? 'Use Script' : 'Apply Tip'}
          </Button>
        </div>
      </CardContent>
    </Card>
  );
};

export default AISuggestionCard;
