// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-practice-sessions.ts
import { createClient } from "npm:@supabase/supabase-js@^2.110.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_practice_sessions_default = defineTool({
  name: "list_practice_sessions",
  title: "List practice sessions",
  description: "List the signed-in user's recent PitchPerfect AI practice sessions (roleplay rounds), most recent first.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).default(10).describe("Maximum number of sessions to return (1-50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).from("practice_sessions").select("id, created_at, industry, scenario_type, difficulty, score, status, duration_seconds").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { sessions: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-practice-session.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.110.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_practice_session_default = defineTool2({
  name: "get_practice_session",
  title: "Get practice session",
  description: "Fetch the full transcript, score, and AI feedback for one of the signed-in user's practice sessions by id.",
  inputSchema: {
    session_id: z2.string().uuid().describe("The practice session id (UUID).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ session_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser2(ctx).from("practice_sessions").select("*").eq("user_id", ctx.getUserId()).eq("id", session_id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Session not found" }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { session: data }
    };
  }
});

// src/lib/mcp/tools/get-user-stats.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.110.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_user_stats_default = defineTool3({
  name: "get_user_stats",
  title: "Get user practice stats",
  description: "Summarize the signed-in user's PitchPerfect AI practice performance: total sessions, average score, best score, and last session date.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser3(ctx).from("practice_sessions").select("score, created_at, status").eq("user_id", ctx.getUserId());
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = data ?? [];
    const scored = rows.filter((r) => typeof r.score === "number");
    const scores = scored.map((r) => r.score);
    const stats = {
      total_sessions: rows.length,
      scored_sessions: scored.length,
      average_score: scores.length ? Math.round(scores.reduce((a, b) => a + b, 0) / scores.length * 100) / 100 : null,
      best_score: scores.length ? Math.max(...scores) : null,
      last_session_at: rows.map((r) => r.created_at).sort().reverse()[0] ?? null
    };
    return {
      content: [{ type: "text", text: JSON.stringify(stats, null, 2) }],
      structuredContent: { stats }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "ggpodadyycvmmxifqwlp";
var mcp_default = defineMcp({
  name: "pitchperfect-ai-mcp",
  title: "PitchPerfect AI",
  version: "0.1.0",
  instructions: "Tools for the signed-in PitchPerfect AI user. Use `list_practice_sessions` to see recent roleplay rounds, `get_practice_session` for the transcript and AI feedback of one round, and `get_user_stats` for an overall performance summary.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_practice_sessions_default, get_practice_session_default, get_user_stats_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
