-- coaching_feedback: per-round AI coaching items generated by score-round
CREATE TABLE IF NOT EXISTS public.coaching_feedback (
  id            UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  round_id      UUID        NOT NULL REFERENCES public.practice_sessions(id) ON DELETE CASCADE,
  user_id       UUID        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  category      TEXT        NOT NULL
    CHECK (category IN ('talk_ratio','objection_step','filler_words','confidence','pace','closing')),
  severity      TEXT        NOT NULL
    CHECK (severity IN ('critical','warning','info')),
  timestamp_sec INT,
  finding_text  TEXT        NOT NULL,
  why_text      TEXT        NOT NULL,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS coaching_feedback_round_idx
  ON public.coaching_feedback (round_id);
CREATE INDEX IF NOT EXISTS coaching_feedback_user_idx
  ON public.coaching_feedback (user_id, created_at DESC);

ALTER TABLE public.coaching_feedback ENABLE ROW LEVEL SECURITY;

CREATE POLICY "coaching_feedback_select_own" ON public.coaching_feedback
  FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "coaching_feedback_insert_service" ON public.coaching_feedback
  FOR INSERT TO service_role WITH CHECK (true);
